spring:
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: update
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/ems?useSSL=false
